version: '3'
services:
#Database SErvice
    webscrapper_db:
        image: mysql:latest
        container_name: webscrapper_db
        restart: always
#        command: --default-authentication-plugin=mysql_native_password
        tty: true
        environment: 
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ./../docker/webscrapper_db:/var/lib/mysql
            - ./../docker/webscrapper_db:/var/lib/mysql-files
            - ./config/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "33061:3306"
            - "33060:33060"
        networks:
            - webscrapper
    webscrapper_db2:
        image: postgres:latest
        container_name: webscrapper_db2
        restart: always
        tty: true
        env_file:
            - ./.env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - TZ=${APP_TIMEZONE}
        volumes:
            - ./../docker/webscrapperpostgres:/var/lib/postgresql
        expose:
            - 5432
        ports:
            - "5439:5432"
        networks:
            - webscrapper
# WEb application api service
 #   webscrapper:
 #       build:
 #           context: .
 #           dockerfile: ./Dockerfile
 #           target: dev
 #       working_dir: /opt/app/api
 #       container_name: webscrapper
 #       restart: always
 #       ports:
 #           - ${SERVER_LISTEN_PORT}:${APP_PORT}
 #       depends_on: 
 #           - webscrapper_db
 #       networks:
 #           - webscrapper
 #      volumes:
 #           - ./:/app
#Docker Networks
networks:
  webscrapper:
    driver: bridge